[package]
name = "statime"
version = "0.1.0"
authors = ["Dion Dokter <dion@tweedegolf.com>", "Ruben Nijveld <ruben@tweedegolf.com>", "David Venhoek <david@tweedegolf.com>"]
license = "MIT OR Apache-2.0"
edition = "2021"
description = "Pure rust implementation of a ptp ordinary clock"
homepage = "https://github.com/tweedegolf/statime"
repository = "https://github.com/tweedegolf/statime"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_enum = { version = "0.5.1", default-features = false }
fixed = "1.11.0"
arrayvec = { version = "0.7.2", default-features = false }
nix = { git = "https://github.com/nix-rust/nix.git", branch = "master" }
time = "0.3.5"
getset = "0.1.2"
libc = { version = "0.2.112", features = ["extra_traits"] }
bitflags = "1.3.2"
ringbuffer = "0.8.2"
thiserror = "1.0.30"
log = "0.4.14"
fern = "0.6.0" # Binary only
chrono = "0.4.19" # Binary only
