[workspace]
members = [
    "ntp-daemon",
    "ntp-ctl",
    "ntp-metrics-exporter",
    "ntp-proto",
    "ntp-os-clock",
    "ntp-udp",
    "test-binaries",
]
exclude = [ ]

# Without the `-p` flag, cargo ignores `--no-default-features` when you have a
# workspace, and without `resolver = "2"` here, you can't use `-p` like this.
resolver = "2"

# Because of the async runtime, we really want panics to cause an abort, otherwise
# the binary can keep on running as a ghost
[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[workspace.dependencies]
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter", "serde", "json"] }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"
rand = "0.8.5"
exitcode = "1.1.2"
arbitrary = { version = "1.2.3" }
thiserror = "1.0.39"
libc = "0.2.139"
tokio = "1.26.0"
toml = "0.7.2"
clap = { version = "4.1.8", features = ["derive", "env"] }
async-trait = "0.1.64"

# sentry
sentry = { version = "0.29.2", default-features = false, features = ["backtrace", "contexts", "panic", "reqwest", "rustls"] }
sentry-tracing = { version = "0.29.2" }

# prometheus support
axum = "0.6.9"
prometheus-client = "0.19.0"

# TLS
rustls = "0.20.8"
rustls-pemfile = "1.0.2"
rustls-native-certs = "0.6.2"
webpki = "0.22.0"

# crypto
aead = "0.5.1"
aes-siv = "0.7.0"
# Note: md5 is needed to calculate ReferenceIDs for IPv6 addresses per RFC5905
md-5 = "0.10.5"
