[workspace]
members = [
    "ntp-proto",
    "nts-pool-ke",
    "ntpd"
]
exclude = [ ]

# Without the `-p` flag, cargo ignores `--no-default-features` when you have a
# workspace, and without `resolver = "2"` here, you can't use `-p` like this.
resolver = "2"

# Global settings for our crates
[workspace.package]
version = "1.4.0"
edition = "2021"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/pendulum-project/ntpd-rs"
homepage = "https://github.com/pendulum-project/ntpd-rs"
readme = "./README.md"
description = "Full-featured implementation of NTP with NTS support"
publish = true
rust-version = "1.70" # MSRV

# Because of the async runtime, we really want panics to cause an abort, otherwise
# the binary can keep on running as a ghost
[profile.dev]
panic = "abort"

[profile.release]
lto = true
panic = "abort"
debug = 2

[workspace.dependencies]
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.0", default-features = false, features = ["std", "fmt", "ansi"] }
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0"
serde_test = "1.0.176"
rand = "0.8.0"
arbitrary = { version = "1.0" }
libc = "0.2.145"
tokio = "1.32"
toml = { version = ">=0.6.0,<0.9.0", default-features = false, features = ["parse"] }
async-trait = "0.1.67"
timestamped-socket = "0.2.2"
clock-steering = "0.2.1"
pps-time = "0.2.3"

# TLS
rustls23 = { package = "rustls", version = "0.23.0", default-features = false, features = ["ring", "logging", "std", "tls12"] }
rustls22 = { package = "rustls", version = "0.22.0", default-features = false, features = ["ring", "logging", "tls12"] }
rustls21 = { package = "rustls", version = "0.21.0" }
rustls-pemfile1 = { package = "rustls-pemfile", version = "1.0" }
rustls-pemfile2 = { package = "rustls-pemfile", version = "2.0" }
rustls-pki-types = "1.2"
rustls-native-certs6 = { package = "rustls-native-certs", version = "0.6" }
rustls-native-certs7 = { package = "rustls-native-certs", version = "0.7" }
tokio-rustls = { version = "0.26.0", default-features = false, features = ["ring", "logging", "tls12"] } # testing only

# crypto
aead = "0.5.0"
aes-siv = "0.7.0"
# Note: md5 is needed to calculate ReferenceIDs for IPv6 addresses per RFC5905
md-5 = "0.10.0"
zeroize = "1.7"

# our own crates used as dependencies, same version as the workspace version
# NOTE: keep this part at the bottom of the file, do not change this line
ntp-proto = { version = "1.4.0", path = "./ntp-proto", default-features = false, features = ["__internal-api"] }
