[workspace]
members = [
    "ntp-daemon",
    "ntp-ctl",
    "ntp-metrics-exporter",
    "ntp-proto",
    "ntp-os-clock",
    "ntp-udp",
    "test-binaries",
    "ntpd"
]
exclude = [ ]

# Without the `-p` flag, cargo ignores `--no-default-features` when you have a
# workspace, and without `resolver = "2"` here, you can't use `-p` like this.
resolver = "2"

# Global settings for our crates
[workspace.package]
version = "0.3.2"
edition = "2021"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/pendulum-project/ntpd-rs"
homepage = "https://github.com/pendulum-project/ntpd-rs"
readme = "./README.md"
description = "Full-featured implementation of NTP with NTS support"
publish = true

[workspace.metadata.release]
sign-commit = true
sign-tag = true
shared-version = true
consolidate-commits = true
tag = false

# Because of the async runtime, we really want panics to cause an abort, otherwise
# the binary can keep on running as a ghost
[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[workspace.dependencies]
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter", "serde", "json"] }
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"
rand = "0.8.5"
exitcode = "1.1.2"
arbitrary = { version = "1.3.0" }
thiserror = "1.0.40"
libc = "0.2.141"
tokio = "1.27.0"
toml = "0.7.3"
clap = { version = "4.2.2", features = ["derive", "env"] }
async-trait = "0.1.68"

# our own crates used as dependencies, same version as the workspace version
ntp-ctl = { version = "0.3.2", path = "./ntp-ctl" }
ntp-daemon = { version = "0.3.2", path = "./ntp-daemon" }
ntp-metrics-exporter = { version = "0.3.2", path = "./ntp-metrics-exporter" }
ntp-os-clock = { version = "0.3.2", path = "./ntp-os-clock" }
ntp-proto = { version = "0.3.2", path = "./ntp-proto" }
ntp-udp = { version = "0.3.2", path = "./ntp-udp" }

# sentry
sentry = { version = "0.29.3", default-features = false, features = ["backtrace", "contexts", "panic", "reqwest", "rustls"] }
sentry-tracing = { version = "0.29.3" }

# prometheus support
axum = "0.6.16"
prometheus-client = "0.19.0"

# TLS
rustls = "0.21.0"
rustls-pemfile = "1.0.2"
rustls-native-certs = "0.6.2"

# crypto
aead = "0.5.2"
aes-siv = "0.7.0"
# Note: md5 is needed to calculate ReferenceIDs for IPv6 addresses per RFC5905
md-5 = "0.10.5"
zeroize = "1.6.0"
