[package]
name = "test-binaries"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0 OR MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.19.2", features = ["full"] }
futures = "0.3.21"
ntp-proto = { path = "../ntp-proto" }
ntp-udp = { path = "../ntp-udp" }
ntp-daemon = { path = "../ntp-daemon" }
ntp-os-clock = { path = "../ntp-os-clock" }
tracing = "0.1.35"
tracing-subscriber = "0.3.11"
serde_json = "1.0.81"
