[package]
name = "test-binaries"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0 OR MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.21.0", features = ["full"] }
ntp-proto = { path = "../ntp-proto" }
ntp-udp = { path = "../ntp-udp" }
ntp-daemon = { path = "../ntp-daemon" }
ntp-os-clock = { path = "../ntp-os-clock" }
tracing = "0.1.36"
tracing-subscriber = "0.3.15"
serde_json = "1.0.85"
clap = { version = "3.2.21", features = ["derive", "env"] }
