[package]
name = "test-binaries"
version = "0.2.1"
edition = "2021"
license = "Apache-2.0 OR MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.24.1", features = ["full"] }
ntp-proto = { path = "../ntp-proto", features = ["ext-test"] }
ntp-udp = { path = "../ntp-udp" }
ntp-daemon = { path = "../ntp-daemon" }
ntp-os-clock = { path = "../ntp-os-clock" }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
serde_json = "1.0.91"
clap = { version = "4.1.3", features = ["derive", "env"] }
rustls-native-certs = "0.6.2"
tokio-rustls = "0.23.4"
aes-siv = "0.7.0"
