[package]
name = "ntp-proto"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0 OR MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
fuzz = []
ext-test = []

[dependencies]
md-5 = "0.10.1"
rand = "0.8.5"
tracing = "0.1.35"
serde = { version = "1.0.137", features = ["derive"] }
