[package]
name = "ntp-proto"
version = "0.2.1"
edition = "2021"
license = "Apache-2.0 OR MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
fuzz = ["arbitrary"]
ext-test = []
new-algorithm = []

[dependencies]
# Note: md5 is needed to calculate ReferenceIDs for IPv6 addresses per RFC5905
md-5.workspace = true
rand.workspace = true
tracing.workspace = true
serde.workspace = true
exitcode.workspace = true
arbitrary = { workspace = true, optional = true }
rustls.workspace = true
thiserror.workspace = true
aead.workspace = true
aes-siv.workspace = true

[dev-dependencies]
rustls-pemfile.workspace = true
