[package]
name = "ntp-proto"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0 OR MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
fuzz = []
ext-test = []

[dependencies]
# Note: md5 is needed to calculate ReferenceIDs for IPv6 addresses per RFC5905
md-5 = "0.10.5"
rand = "0.8.5"
tracing = "0.1.37"
serde = { version = "1.0.145", features = ["derive"] }
exitcode = "1.1.2"
