[package]
name = "statime-linux"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrayvec = { version = "0.7.3", default-features = false }
bitflags = "2.3.2"
chrono = "0.4.26"
clap = { version = "4.3.3", features = ["derive"] }
fern = { version = "0.6.2", features = ["colored"] }
fixed = "1.23.1"
libc = { version = "0.2.146", features = ["extra_traits"] }
log = "0.4.19"
statime = { path = "../statime" }
thiserror = "1.0.40"
tokio = { version = "1.28", features = ["full"] }
