name: Generate documentation
on:
    push:
        branches:
            - main

jobs:
    doc:
        runs-on: ubuntu-latest
        permissions:
            contents: write  # To push a branch
            pull-requests: write  # To create a PR from that branch
        steps:
            -   uses: actions/checkout@v3
                with:
                    fetch-depth: 0
            -   name: Install latest mdbook
                run: |
                    tag=$(curl 'https://api.github.com/repos/rust-lang/mdbook/releases/latest' | jq -r '.tag_name')
                    url="https://github.com/rust-lang/mdbook/releases/download/${tag}/mdbook-${tag}-x86_64-unknown-linux-gnu.tar.gz"
                    mkdir mdbook
                    curl -sSL $url | tar -xz --directory=./mdbook
                    echo `pwd`/mdbook >> $GITHUB_PATH
            -   name: Install rust
                uses: actions-rs/toolchain@v1
            -   name: Generate reference manual
                run: mdbook build docs
            -   name: Generate API documentation
                run: cargo doc --workspace --target-dir docs/api
            -   name: Deploy GitHub Pages
                run: |
                    cd docs
                    git worktree add gh-pages
                    git config user.name "Deploy from CI"
                    git config user.email ""
                    cd gh-pages
                    git update-ref -d refs/heads/gh-pages
                    rm -rf *
                    mv ../book/* .
                    mkdir docs
                    mv ../api/doc/* docs
                    git add .
                    git commit -m "Deploy $GITHUB_SHA to gh-pages"
                    git push --force --set-upstream origin gh-pages
